// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: numbers.proto

package ru.hse.java.numbers.protos;

public final class NumbersProtos {
  private NumbersProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Numbers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Numbers_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnumbers.proto\"\032\n\007Numbers\022\017\n\007numbers\030\001 " +
      "\003(\005B-\n\032ru.hse.java.numbers.protosB\rNumbe" +
      "rsProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Numbers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Numbers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Numbers_descriptor,
        new java.lang.String[] { "Numbers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
